### ISSUE TITLE
Duplicate files

### ISSUE THREAD

**Issue by moyogo** [docrepair-fonts/lunasima-fonts#1]
[sources/Lunasima-Regular.designspace](https://github.com/docrepair-fonts/lunasima-fonts/blob/main/sources/Lunasima-Regular.designspace) and [sources/lunasima-Regular.designspace](https://github.com/docrepair-fonts/lunasima-fonts/blob/main/sources/lunasima-Regular.designspace) are duplicates.

**Comment by twardoch** [comment]
Hmm. I guess Git doesn't like renaming that changes case but I have no idea how to fix it

**Comment by twardoch** [comment]
Ok, I removed it using GH, I hope that does it
