### ISSUE TITLE
Mis-shaped Polytonic Greek

### ISSUE THREAD

**Issue by yanone** [docrepair-fonts/lunasima-fonts#2]
Old:

![Bildschirmfoto 2023-04-12 um 11 09 48](https://user-images.githubusercontent.com/175386/231410928-a472d5ba-69df-48a2-8f51-4c55c388fa8f.jpg)

New:

![Bildschirmfoto 2023-04-12 um 11 09 56](https://user-images.githubusercontent.com/175386/231410905-2130cf2d-a365-4c2c-94ca-5c42d09d3070.jpg)

**Comment by twardoch** [comment]
Removed polytonic Greek & rebuilt
